name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 3.1.x
        
    - name: Build
      run: dotnet build ./RestAssuredExamples/uebungen/uebungen.csproj
    - name: Test
      run: dotnet test ./RestAssuredExamples/uebungen/uebungen.csproj --no-build --logger trx --results-directory "TestResults"
      
    - name: Upload dotnet test results
      uses: actions/upload-artifact@v3
      with:
        name: dotnet-results
        path: TestResults
      if: ${{ always() }}
      
    - name: Test Report
      uses: dorny/test-reporter@v1
      if: ${{ always() }}
      with:
        name: .NET Tests            
        path: TestResults/*.trx    # Path to test results
        reporter: dotnet-trx
